---
extends:
- plugin:react/recommended
env:
  browser: true
  es6: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
  sourceType: module
plugins:
- "@typescript-eslint"
- "@typescript-eslint/eslint-plugin-tslint"
- import
- prefer-arrow
- react
- unused-imports
settings:
  react:
    version: detect
rules:
  "@typescript-eslint/adjacent-overload-signatures": error
  "@typescript-eslint/array-type": error
  "@typescript-eslint/ban-types": error
  "@typescript-eslint/consistent-type-assertions": error
  "@typescript-eslint/consistent-type-definitions": error
  "@typescript-eslint/explicit-member-accessibility":
  - error
  - accessibility: explicit
  "@typescript-eslint/indent":
  - error
  - tab
  - CallExpression:
      arguments: first
    FunctionDeclaration:
      parameters: first
    FunctionExpression:
      parameters: first
    SwitchCase: 1
  "@typescript-eslint/member-delimiter-style":
  - error
  - multiline:
      delimiter: semi
      requireLast: true
    singleline:
      delimiter: semi
      requireLast: false
  "@typescript-eslint/member-ordering": error
  "@typescript-eslint/naming-convention":
  - error
  - selector: default
    format:
    - strictCamelCase
  - selector: variable
    format:
    - strictCamelCase
    - StrictPascalCase
  - selector: class
    format:
    - StrictPascalCase
  - selector: enum
    format:
    - StrictPascalCase
  - selector: interface
    format:
    - StrictPascalCase
  - selector: typeAlias
    format:
    - StrictPascalCase
  - selector: typeParameter
    format:
    - PascalCase
  - selector: property
    modifiers:
    - static
    - readonly
    format:
    - UPPER_CASE
  "@typescript-eslint/no-empty-function": error
  "@typescript-eslint/no-empty-interface": error
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-misused-new": error
  "@typescript-eslint/no-namespace": error
  "@typescript-eslint/no-parameter-properties": "off"
  "@typescript-eslint/no-this-alias": error
  "@typescript-eslint/no-use-before-define": "off"
  "@typescript-eslint/no-var-requires": error
  "@typescript-eslint/prefer-for-of": error
  "@typescript-eslint/prefer-function-type": error
  "@typescript-eslint/prefer-namespace-keyword": error
  "@typescript-eslint/quotes":
  - error
  - double
  "@typescript-eslint/semi":
  - error
  - always
  "@typescript-eslint/triple-slash-reference": error
  "@typescript-eslint/tslint/config":
  - error
  - rules:
      import-spacing: true
      jsdoc-format: true
      no-reference-import: true
      object-literal-sort-keys: true
      one-line:
      - true
      - check-catch
      - check-else
      - check-open-brace
      - check-whitespace
      prefer-conditional-expression: true
      typedef:
      - true
      - arrow-call-signature
      - call-signature
      - member-variable-declaration
      - parameter
      - property-declaration
      - variable-declaration
      - variable-declaration-ignore-function
      whitespace:
      - true
      - check-branch
      - check-decl
      - check-module
      - check-operator
      - check-separator
      - check-type
      - check-typecast
  "@typescript-eslint/type-annotation-spacing": error
  "@typescript-eslint/unified-signatures": error
  arrow-body-style: error
  arrow-parens:
  - error
  - as-needed
  camelcase: error
  comma-dangle:
  - error
  - arrays: always-multiline
    objects: always-multiline
    imports: always-multiline
    exports: always-multiline
    functions: always-multiline
  complexity: "off"
  constructor-super: error
  curly: error
  default-case: error
  dot-notation: error
  eol-last: "off"
  eqeqeq:
  - error
  - smart
  guard-for-in: error
  id-blacklist:
  - error
  - any
  - Undefined
  - undefined
  id-match: error
  import/no-absolute-path: 2
  import/no-extraneous-dependencies: error
  import/no-internal-modules: "off"
  import/order:
  - error
  - alphabetize:
      order: asc
    groups:
    - - builtin
      - external
    - parent
    - sibling
    newlines-between: always-and-inside-groups
  lines-between-class-members:
  - error
  - always
  - exceptAfterSingleLine: true
  max-classes-per-file:
  - error
  - 1
  max-len:
  - error
  - code: 120
    ignorePattern: '[`"''](\)*;|\})?$'
    ignoreStrings: true
  new-parens: error
  no-bitwise: error
  no-caller: error
  no-cond-assign: error
  no-console: "off"
  no-debugger: error
  no-duplicate-case: error
  no-duplicate-imports: error
  no-empty: error
  no-eval: error
  no-extra-bind: error
  no-fallthrough: error
  no-invalid-this: "off"
  no-multiple-empty-lines: error
  no-new-func: error
  no-new-wrappers: error
  no-redeclare: error
  no-return-await: error
  no-sequences: error
  no-shadow:
  - error
  - builtinGlobals: true
    hoist: all
  no-sparse-arrays: error
  no-template-curly-in-string: error
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-underscore-dangle:
  - error
  - allow:
    - __PRELOADED_STATE__
    - __REDUX_DEVTOOLS_EXTENSION_COMPOSE__
  no-unsafe-finally: error
  no-unused-expressions: error
  no-unused-labels: error
  no-unused-vars: "off"
  no-var: error
  object-shorthand: error
  one-var:
  - error
  - never
  padding-line-between-statements:
  - error
  - blankLine: always
    prev: "*"
    next: "return"
  prefer-arrow/prefer-arrow-functions: error
  prefer-const: error
  prefer-object-spread: error
  quote-props:
  - error
  - consistent-as-needed
  radix: error
  react/jsx-boolean-value:
  - error
  - always
  react/jsx-curly-spacing: error
  react/jsx-equals-spacing: error
  react/jsx-key: error
  react/jsx-no-bind: "off"
  react/no-string-refs: error
  react/no-unescaped-entities: "off"
  react/prop-types: "off"
  space-before-function-paren:
  - error
  - anonymous: never
    asyncArrow: always
    named: never
  space-in-parens:
  - error
  - never
  spaced-comment: error
  unused-imports/no-unused-imports-ts: 2
  unused-imports/no-unused-vars-ts: 1
  use-isnan: error
  valid-typeof: "off"
