---
about: FAQs
aboutPageTitle: Frequently asked questions
aboutSectionHeaders:
  whatIs: What is {app}?
  contributing: Can I help?
  reportsAndClaims: What are employer claims and reports?
  claimProcessing: How do claims get processed?
  submitClaims: How do I add, change, or dispute claims?
  citationTypes: What does the icon next to a claim mean?
  employerRatings: What determines the rating of an employer?
  layoffsAndFurloughs: What is the difference between a "layoff" and a "furlough"?
aboutSectionParagraphs:
  whatIs: "**{app}** ({appFullName}) is a collaborative, open-source project designed to track the responses of employers to the [coronavirus]({covidWikiUrl}) (COVID-19) [pandemic of 2019&ndash;2020]({pandemicWikiUrl}). It is built using information sourced from a number of places and categorizes it based on how reliable the original information source is considered to be. For more information, please visit [the project's page on GitHub]({githubUrl})."
  contributing: Yes! {app} is open-source and open-data and we'd love to have your help! You can help by submitting new employer claims and changes, or by submitting code changes to the site. See [our submissions page](/submit) for more.
  reportsAndClaims: |
    An **employer claim** is one or more declarations about an employer which include a summary and citations to back it up. This appears as a single bullet-point in the employer's listing.

    An **employer report** is a collection of claims about an employer as well as an overall rating of how well that employer has handled the COVID-19 pandemic crisis.
  claimProcessing: Once a claim is submitted, it must be reviewed by a contributor to the project before it will be approved and appear on the site. This review process will require the contributor to go through each of the sources and validate that the claim made is substantiated by the source. Once the submitter and contributor(s) agree on the submitted information, the claim is completed and will appear the next time the site is updated.
  submitClaims: To submit a claim change of any kind, please click the "{submit}" link in the navigation menu. From there, ou can either submit a request for someone to update our data files, or submit a GitHub pull request to update the files yourself.
  citationTypes: |
    - {publication}: {publicationDescription}
    - {statement}: {statementDescription}
    - {hearsay}: {hearsayDescription}
  employerRatings: Ratings are algorithmically determined based on the positivity and negativity of the claims that it has. Claims that are more safety-critical have a higher weight than those which are not, and thus are not factored as heavily.
  layoffsAndFurloughs: |
    For the purposes of this site, a **furlough** indicates that affected employees are not working, but are still marked as employed by the company. They may receive partial pay or benefits, and are generally expected to be rehired in the future. A **layoff** indicates that affected employees have been terminated from their jobs entirely. A more complete description is available [on Dictionary.com](https://www.dictionary.com/e/furlough-vs-layoff/).

    Some dialects of English use the term "temporary layoff" to describe a furlough, but to avoid confusion, we avoid that term. As a result, information we cite from some sources may be erroneously written as "layoff" when they are instead referring to a furlough. Should you ever run into a situation like this, please submit a correction!
appTitle: Coronavirus Employer Response Tracker
appTitleShort: Cempres
backToTop: Top of page
citationTypeDescriptions:
  publication: Published articles such as a company blog, PR statement, government report, or leaked document.
  statement: Published statements from employees (former, anonymous, or otherwise).
  hearsay: Word-of-mouth, rumors, or unconfirmed information.
citationTypes:
  publication: Publication
  statement: Statement
  hearsay: Hearsay
countryNames:
  af: Afghanistan
  al: Albania
  dz: Algeria
  as: American Samoa
  ad: Andorra
  ao: Angola
  ai: Anguilla
  aq: Antarctica
  ag: Antigua and Barbuda
  ar: Argentina
  am: Armenia
  aw: Aruba
  au: Australia
  at: Austria
  az: Azerbaijan
  bs: Bahamas
  bh: Bahrain
  bd: Bangladesh
  bb: Barbados
  by: Belarus
  be: Belgium
  bz: Belize
  bj: Benin
  bm: Bermuda
  bt: Bhutan
  bo: Bolivia
  ba: Bosnia and Herzegovina
  bw: Botswana
  bv: Bouvet Island
  br: Brazil
  io: British Indian Ocean Territory
  bn: Brunei
  bg: Bulgaria
  bf: Burkina Faso
  bi: Burundi
  kh: Cambodia
  cm: Cameroon
  ca: Canada
  cv: Cape Verde
  ky: Cayman Islands
  cf: Central African Republic
  td: Chad
  cl: Chile
  cn: China
  cx: Christmas Island
  cc: Cocos (Keeling) Islands
  co: Colombia
  km: Comoros
  cg: Congo
  ck: Cook Islands
  cr: Costa Rica
  hr: Croatia
  cu: Cuba
  cy: Cyprus
  cz: Czech Republic
  dk: Denmark
  dj: Djibouti
  dm: Dominica
  do: Dominican Republic
  tp: East Timor
  ec: Ecuador
  eg: Egypt
  sv: El Salvador
  gq: Equatorial Guinea
  er: Eritrea
  ee: Estonia
  et: Ethiopia
  fk: Falkland Islands
  fo: Faroe Islands
  fj: Fiji Islands
  fi: Finland
  fr: France
  gf: French Guiana
  pf: French Polynesia
  tf: French Southern territories
  ga: Gabon
  gm: Gambia
  ge: Georgia
  de: Germany
  gh: Ghana
  gi: Gibraltar
  gr: Greece
  gl: Greenland
  gd: Grenada
  gp: Guadeloupe
  gu: Guam
  gt: Guatemala
  gg: Guernsey
  gn: Guinea
  gw: Guinea-Bissau
  gy: Guyana
  ht: Haiti
  hm: Heard Island and McDonald Islands
  va: Holy See (Vatican City State)
  hn: Honduras
  hk: Hong Kong
  hu: Hungary
  is: Iceland
  in: India
  id: Indonesia
  ir: Iran
  iq: Iraq
  ie: Ireland
  im: Isle of Man
  il: Israel
  it: Italy
  ci: Ivory Coast
  jm: Jamaica
  jp: Japan
  je: Jersey
  jo: Jordan
  kz: Kazakhstan
  ke: Kenya
  ki: Kiribati
  kw: Kuwait
  kg: Kyrgyzstan
  la: Laos
  lv: Latvia
  lb: Lebanon
  ls: Lesotho
  lr: Liberia
  ly: Libyan Arab Jamahiriya
  li: Liechtenstein
  lt: Lithuania
  lu: Luxembourg
  mo: Macao
  mk: North Macedonia
  mg: Madagascar
  mw: Malawi
  my: Malaysia
  mv: Maldives
  ml: Mali
  mt: Malta
  mh: Marshall Islands
  mq: Martinique
  mr: Mauritania
  mu: Mauritius
  yt: Mayotte
  mx: Mexico
  fm: Micronesia, Federated States of
  md: Moldova
  mc: Monaco
  mn: Mongolia
  me: Montenegro
  ms: Montserrat
  ma: Morocco
  mz: Mozambique
  mm: Myanmar
  na: Namibia
  nr: Nauru
  np: Nepal
  nl: Netherlands
  an: Netherlands Antilles
  nc: New Caledonia
  nz: New Zealand
  ni: Nicaragua
  ne: Niger
  ng: Nigeria
  nu: Niue
  nf: Norfolk Island
  kp: North Korea
  mp: Northern Mariana Islands
  'no': Norway
  om: Oman
  pk: Pakistan
  pw: Palau
  ps: Palestine
  pa: Panama
  pg: Papua New Guinea
  py: Paraguay
  pe: Peru
  ph: Philippines
  pn: Pitcairn
  pl: Poland
  pt: Portugal
  pr: Puerto Rico
  qa: Qatar
  re: Reunion
  ro: Romania
  ru: Russian Federation
  rw: Rwanda
  sh: Saint Helena
  kn: Saint Kitts and Nevis
  lc: Saint Lucia
  pm: Saint Pierre and Miquelon
  vc: Saint Vincent and the Grenadines
  ws: Samoa
  sm: San Marino
  st: Sao Tome and Principe
  sa: Saudi Arabia
  sn: Senegal
  rs: Serbia
  sc: Seychelles
  sl: Sierra Leone
  sg: Singapore
  sk: Slovakia
  si: Slovenia
  sb: Solomon Islands
  so: Somalia
  za: South Africa
  gs: South Georgia and the South Sandwich Islands
  kr: South Korea
  ss: South Sudan
  es: Spain
  lk: Sri Lanka
  sd: Sudan
  sr: Suriname
  sj: Svalbard and Jan Mayen
  sz: Swaziland
  se: Sweden
  ch: Switzerland
  sy: Syria
  tj: Tajikistan
  tz: Tanzania
  th: Thailand
  cd: The Democratic Republic of Congo
  tl: Timor-Leste
  tg: Togo
  tk: Tokelau
  to: Tonga
  tt: Trinidad and Tobago
  tn: Tunisia
  tr: Turkey
  tm: Turkmenistan
  tc: Turks and Caicos Islands
  tv: Tuvalu
  ug: Uganda
  ua: Ukraine
  ae: United Arab Emirates
  gb: United Kingdom
  us: United States
  um: United States Minor Outlying Islands
  uy: Uruguay
  uz: Uzbekistan
  vu: Vanuatu
  ve: Venezuela
  vn: Vietnam
  vg: Virgin Islands, British
  vi: Virgin Islands, U.S.
  wf: Wallis and Futuna
  eh: Western Sahara
  ye: Yemen
  yu: Yugoslavia
  zm: Zambia
  zw: Zimbabwe
detailDescriptions:
  aka: Alternative names for the employer, including aliases, parent companies, and child companies.
  edit: The employer's data file where edits can be made.
  employees: The approximate number of employees the company had prior to the Coronavirus pandemic.
  industry: The industries in which the employer is active.
  linkToEmployer: The link directly to this employer's profile.
  location: Where the employer's headquarters are located.
  name: The incorporated name of the employer.
  officialWebsite: The employer's official website link.
  rating: The general rating of the employer.
  ratingCounts: Aggregate counts of the good and bad actions an employer has taken.
  ticker: The ticker symbol of the employee's publicly traded stock.
  wikipedia: The employer's page on the English Wikipedia.
detailLabels:
  officialWebsite: Homepage
  wikipedia: "{page} on Wikipedia"
employeeDelta: "{change} since {date}"
employerList: Employers
employerUpdatedDate: Last updated {date}
filter: Filters
filters:
  employeesDefault: Size
  employeesSmall: Small
  employeesMedium: Medium
  employeesLarge: Large
  locationDefault: Operations
  locationNational: National
  locationInternational: Multinational
home: Home
homeFormLink: Open the form!
homeListLink: Take me to the list!
homeSampleDescription: Each card shows you briefly **who** the employer is, a **rating** of their general response, and a **summary** about the actions they've taken. You can also open up a more detailed view to find **cited news articles**, or click various **links** to go on Wikipedia, or see the employer's official website.
homeSampleTitle: What can I learn?
homeSubmitDescription: The easiest way to submit new information is by following the link below to our submission form. To learn more about this or other ways to contribute, please check out [our submissions page](/submit).
homeSubmitTitle: Can I add new info?
homeSubtitleText: A free, open-data collection on [{count} employers](/employers) (and growing) and how they've reacted to the COVID-19 crisis.
industries:
  advertising: Advertising
  agriculture: Agriculture
  airline: Airline
  apparel: Apparel
  automotive: Automotive
  aviation: Aviation
  cannabis: Cannabis
  childCare: Child care
  clothing: Clothing
  coffeeShop: Coffee shop
  construction: Construction
  cosmetics: Cosmetics
  courier: Courier
  eCommerce: E-commerce
  education: Education
  electronics: Electronics
  energy: Energy
  engineering: Engineering
  entertainment: Entertainment
  financialServices: Financial services
  fishing: Fishing
  foodDelivery: Food delivery
  foodProcessing: Food processing
  furniture: Furniture
  groceryStore: Grocery
  healthAndFitness: Health and fitness
  healthCare: Healthcare
  hemp: Hemp
  hospitality: Hospitality
  industrial: Industrial
  insurance: Insurance
  internet: Internet
  landDevelopment: Land development
  lodging: Lodging
  manufacturing: Manufacturing
  media: Media
  mining: Mining
  packaging: Packaging
  plastics: Plastics
  procurement: Procurement
  publicUtilities‎: Public utilities‎
  publishing: Publishing
  rail: Rail
  realEstate: Real estate
  restaurant: Restaurant
  retail: Retail
  sanitation: Sanitation
  signage: Signage
  software: Software
  sports: Sports
  storage: Storage
  technology: Technology
  telecommunications: Telecommunications
  textile: Textile
  ticketSales: Ticket sales
  tourism: Tourism
  transport: Transport
  videoGames: Video games
  waste: Waste
  water: Water
linkTypes:
  children: Subsidiaries
  parent: Parent company
  related: Related
loading: Loading...
loadMore: Load {count} more
more: "{number} more"
noResults: No results.
noSources: Word of mouth; no citation
notFound: Not found.
profile: Employer profile
ratingLabels:
  poor: Poor
  fair: Fair
  good: Good
readMore: Read more
search: Search
submit: Submit
submitCodeGithub:
  description: We'd love to see your ideas on how to shape this website. Just fork **our GitHub repository** and start a pull request to submit your code changes.
  title: Submit code via GitHub
submitDataForm:
  description: The easiest way to submit new employers or edit existing ones is through our **online Google form**. Just fill out a few fields and we'll make the changes behind the scenes.
  title: Submit data via form
submitDataGithub:
  description: Another way to add or update employers is through our **GitHub issues page**. Just open an issue or make the change yourself and start a pull request.
  title: Submit data via GitHub
submitSubtitle: "**{appTitle}** is completely open-data and open-source. We would love to accept your new employer entries, new details or claims, or your code changes. Have a look at the options below to see how you can help shape our future!"
submitTitle: Submitting new information
