name: Deploy to Azure

on:
  release:
    types: [created]

env:
  AZURE_WEBAPP_NAME: cempres
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '10.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        yarn install
        yarn build
        # Test -- disabled for now. # yarn test --watchAll=false
      env:
        RAZZLE_PUBLIC_DIR: /home/site/wwwroot/build/public
        PORT: 8080
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        slot-name: ${{ secrets.AZURE_DEPLOYMENT_SLOT }}
