name: Continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      run: yarn install
    - name: Run linting
      run: |
        yarn lint:ts
        echo "Lint process exited with status code $?."
    - name: Build
      run: |
        CI=true yarn build
        echo "Build process exited with status code $?."
    - name: Run unit tests
      run: |
        yarn test:ci
        echo "Test process exited with status code $?."
